Materials
Leibniz-HBI/telegram-workshop pull request #1
Opened 2024-01-31 15:25 UTC by nielslukaslange

2024-02-02 16:23 UTC, FlxVctr commented
@JanRau: kannst du bitte inhaltlich draufschauen und ändern/kommentieren & in main mergen? Ggf. Unterstützung von @pekasen anfragen. Dann kann das mit der Survey (wenn die gut aussieht) zusammen raus. Danke!

2024-02-05 19:57 UTC, pekasen commented on docs/index.md
> +Abschließend folgte eine Panel-Diskussion der Vortragenden.
Hier ist die URL für alle Einträge die gleiche und linkt auf den main-Branch von dem Repo. Wäre es nicht cool, die Vorträge gleich zu verlinken?

2024-02-05 19:59 UTC, pekasen requested changes
Bitte noch mal auf die Links zu den Vorträgen im README schauen, danke! :)

2024-02-06 10:29 UTC, nielslukaslange commented on docs/index.md
> +Abschließend folgte eine Panel-Diskussion der Vortragenden.
Ja! Das waren meine Platzhalter-Links, weil wir ja noch auf ein paar Antworten der Vortragenden gewartet haben. Mittlerweile sind da die richtigen Folien verlinkt.

2024-02-06 10:34 UTC, pekasen approved these changes

2024-02-06 10:35 UTC, pekasen commented on docs/index.md
> +Abschließend folgte eine Panel-Diskussion der Vortragenden.
Tiptop, das sieht gut aus! :)

2024-02-15 10:40 UTC, merged